# Generated by Django 5.2.1 on 2026-04-30 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(verbose_name='Задание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата задачи')),
                ('finished', models.DateTimeField(auto_now_add=True, verbose_name='Дата сдачи')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.schoolgroups', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашнее задание',
            },
        ),
        migrations.CreateModel(
            name='HomeWorkStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.homework', verbose_name='Домашнее задание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Домашнее задание для учеников',
                'verbose_name_plural': 'Домашнее задание для учеников',
            },
        ),
    ]
