# Generated by Django 5.2.1 on 2026-05-20 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="lead",
            new_name="sales_lead_status_4b2468_idx",
            old_name="sales_lead_status_20fd90_idx",
        ),
        migrations.RenameIndex(
            model_name="lead",
            new_name="sales_lead_assigne_c6b285_idx",
            old_name="sales_lead_assigne_9d63c7_idx",
        ),
        migrations.RenameIndex(
            model_name="lead",
            new_name="sales_lead_next_co_c2405e_idx",
            old_name="sales_lead_next_co_2cdd31_idx",
        ),
        migrations.RenameIndex(
            model_name="lead",
            new_name="sales_lead_source_4744a0_idx",
            old_name="sales_lead_source_e407f2_idx",
        ),
    ]
