# Generated by Django 5.2.1 on 2026-05-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_legacy_order_payment_related_name"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="order",
            new_name="sales_order_status_72c80a_idx",
            old_name="sales_order_status_4c8d9e_idx",
        ),
        migrations.RenameIndex(
            model_name="order",
            new_name="sales_order_paid_at_32f711_idx",
            old_name="sales_order_paid_at_1a5d4b_idx",
        ),
        migrations.RenameIndex(
            model_name="orderitem",
            new_name="sales_order_item_ty_ac87c0_idx",
            old_name="sales_order_item_ty_99da03_idx",
        ),
        migrations.RenameIndex(
            model_name="orderitem",
            new_name="sales_order_schedul_5f483e_idx",
            old_name="sales_order_schedul_d5481a_idx",
        ),
        migrations.RenameIndex(
            model_name="orderitem",
            new_name="sales_order_lesson__863ae3_idx",
            old_name="sales_order_lesson__308c6b_idx",
        ),
        migrations.RenameIndex(
            model_name="orderitem",
            new_name="sales_order_subscri_e9fcba_idx",
            old_name="sales_order_subscri_8b1332_idx",
        ),
    ]
