# Generated by Django 5.2.1 on 2026-05-02 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_total', models.IntegerField(verbose_name='Всего занятий')),
                ('lessons_used', models.IntegerField(default=0, verbose_name='Использовано занятий')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('expired', 'Истек срок'), ('exhausted', 'Исчерпан'), ('frozen', 'Заморожен')], default='active', max_length=20, verbose_name='Статус')),
                ('frozen_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата заморозки')),
                ('frozen_days', models.IntegerField(default=0, verbose_name='Дней заморожен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Родитель (покупатель)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта'), ('transfer', 'Банковский перевод'), ('online', 'Онлайн-оплата')], max_length=20, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('completed', 'Оплачен'), ('failed', 'Ошибка'), ('refunded', 'Возврат')], default='pending', max_length=20, verbose_name='Статус')),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID транзакции')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Плательщик')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название тарифа')),
                ('lessons_count', models.IntegerField(verbose_name='Количество занятий')),
                ('validity_days', models.IntegerField(verbose_name='Срок действия (дней)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен для покупки')),
                ('is_trial', models.BooleanField(default=False, verbose_name='Пробный тариф')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='courses.courses', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['course', 'lessons_count'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.tariff', verbose_name='Тариф'),
        ),
        migrations.CreateModel(
            name='LessonAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Присутствовал'), ('absent', 'Отсутствовал'), ('excused', 'Уважительная причина')], max_length=20, verbose_name='Статус посещения')),
                ('lessons_count', models.IntegerField(choices=[(1, '1 занятие (45 минут)'), (2, '2 занятия (90 минут)')], default=2, verbose_name='Количество занятий')),
                ('lesson_deducted', models.BooleanField(default=False, verbose_name='Занятие списано')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Кто отметил')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='schedule.schedule', verbose_name='Занятие')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='subscriptions.subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемость',
                'ordering': ['-created_at'],
                'unique_together': {('schedule', 'student')},
            },
        ),
    ]
