# Generated by Django 5.2.1 on 2026-05-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Сообщение об ошибке'),
        ),
        migrations.AddField(
            model_name='payment',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='ID платежа ЮKassa'),
        ),
        migrations.AddField(
            model_name='payment',
            name='yookassa_payment_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL для оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('completed', 'Оплачен'), ('failed', 'Ошибка'), ('refunded', 'Возврат'), ('canceled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
