# Generated by Django 5.2.1 on 2026-05-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_payment_error_message_payment_yookassa_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('active', 'Активный'), ('expired', 'Истек срок'), ('exhausted', 'Исчерпан'), ('frozen', 'Заморожен'), ('canceled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
