# Generated by Django 5.2.1 on 2025-06-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_fio', models.CharField(max_length=150, verbose_name='ФИО родителя')),
                ('child_fio', models.CharField(max_length=150, verbose_name='ФИО ребенка')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('age', models.IntegerField(max_length=3, verbose_name='Возраст ребенка')),
                ('courses', models.CharField(max_length=250, verbose_name='Выбранные курсы')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время обращения')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
