# Generated by Django 5.2.1 on 2025-06-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantrequest',
            name='age',
            field=models.CharField(max_length=3, verbose_name='Возраст ребенка'),
        ),
    ]
