# Generated by Django 5.2.1 on 2025-06-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_participantrequest_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participantrequest',
            options={'ordering': ('-created',), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='participantrequest',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
