# Generated by Django 5.2.1 on 2026-04-30 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_participantrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participantrequest',
            options={'ordering': ('-created',), 'verbose_name': 'Заявку', 'verbose_name_plural': 'Заявки'},
        ),
    ]
