# Generated by Django 5.2.1 on 2026-05-01 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('main', '0004_alter_participantrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantrequest',
            name='phone',
            field=models.CharField(default='+70000000000', max_length=20, validators=[django.core.validators.RegexValidator(message='Номер телефона должен начинаться с +7 и содержать 10 цифр после него (например: +79001234567)', regex='^\\+7\\d{10}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='participantrequest',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Обработана'),
        ),
        migrations.RemoveField(
            model_name='participantrequest',
            name='courses',
        ),
        migrations.AlterField(
            model_name='participantrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта (необязательно)'),
        ),
        migrations.AddField(
            model_name='participantrequest',
            name='courses',
            field=models.ManyToManyField(related_name='participant_requests', to='courses.courses', verbose_name='Выбранные курсы'),
        ),
    ]
