# Generated by Django 5.2.1 on 2026-05-20 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="task",
            new_name="tasks_task_assigne_bd468b_idx",
            old_name="tasks_task_assigne_495f98_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="tasks_task_status_1f2475_idx",
            old_name="tasks_task_status_58dbd7_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="tasks_task_task_ty_45f0a7_idx",
            old_name="tasks_task_task_ty_5656a6_idx",
        ),
    ]
