# Generated by Django 5.2.1 on 2026-04-30 21:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classdateStart', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время начала')),
                ('classdateEnd', models.TimeField(default=django.utils.timezone.now, verbose_name='Дата и время окончания')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.schoolgroups', verbose_name='Группа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
    ]
