# Generated by Django 5.2.1 on 2026-05-02 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_schoolgroups_is_active'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='original_classdateEnd',
            field=models.TimeField(blank=True, null=True, verbose_name='Изначальное время окончания'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='original_classdateStart',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Изначальная дата и время начала'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='reschedule_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина переноса'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланировано'), ('cancelled', 'Отменено'), ('rescheduled', 'Перенесено')], default='scheduled', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='GroupScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('lessons_count', models.PositiveSmallIntegerField(choices=[(1, '1 занятие (45 минут)'), (2, '2 занятия (90 минут)')], default=2, verbose_name='Количество занятий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный шаблон')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to='groups.schoolgroups', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Шаблон расписания группы',
                'verbose_name_plural': 'Шаблоны расписания групп',
                'ordering': ['weekday', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('group', 'weekday', 'start_time'), name='unique_group_schedule_template')],
            },
        ),
    ]
