# Generated by Django 5.2.1 on 2026-05-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланировано'), ('completed', 'Прошло'), ('cancelled', 'Отменено'), ('rescheduled', 'Перенесено')], default='scheduled', max_length=20, verbose_name='Статус'),
        ),
    ]
