# Generated by Django 5.2.1 on 2026-05-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0008_lessonparticipant_billing_links"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="lesson",
            new_name="schedule_le_starts__f2555b_idx",
            old_name="schedule_le_starts__baf9d0_idx",
        ),
        migrations.RenameIndex(
            model_name="lesson",
            new_name="schedule_le_status_60b5f4_idx",
            old_name="schedule_le_status_375573_idx",
        ),
        migrations.RenameIndex(
            model_name="lesson",
            new_name="schedule_le_teacher_4ec590_idx",
            old_name="schedule_le_teacher_17f6e3_idx",
        ),
        migrations.RenameIndex(
            model_name="lesson",
            new_name="schedule_le_group_i_f463ab_idx",
            old_name="schedule_le_group_i_7aa109_idx",
        ),
        migrations.RenameIndex(
            model_name="lesson",
            new_name="schedule_le_course__6620b2_idx",
            old_name="schedule_le_course__520b82_idx",
        ),
        migrations.RenameIndex(
            model_name="lessonparticipant",
            new_name="schedule_le_student_7207a9_idx",
            old_name="schedule_le_student_fbe113_idx",
        ),
        migrations.RenameIndex(
            model_name="lessonparticipant",
            new_name="schedule_le_lesson__f0d03c_idx",
            old_name="schedule_le_lesson__0808b9_idx",
        ),
        migrations.RenameIndex(
            model_name="lessonparticipant",
            new_name="schedule_le_subscri_6c011f_idx",
            old_name="schedule_le_subscri_9a86a0_idx",
        ),
        migrations.RenameIndex(
            model_name="lessonparticipant",
            new_name="schedule_le_order_i_5e95ba_idx",
            old_name="schedule_le_order_i_5dcdd4_idx",
        ),
    ]
