# Generated by Django 5.2.1 on 2026-05-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_make_email_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон родителя'),
        ),
    ]
