# Generated by Django 5.2.1 on 2026-05-02 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='parent_phone',
        ),
    ]
